/*
 * Decompiled with CFR 0.152.
 */
package okhttp3;

public final class CipherSuite
extends Enum<CipherSuite> {
    private static final CipherSuite[] $VALUES;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_AES_256_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_DHE_DSS_WITH_DES_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_AES_256_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_DHE_RSA_WITH_DES_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DH_anon_EXPORT_WITH_RC4_40_MD5;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_AES_256_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_DES_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_DH_anon_WITH_RC4_128_MD5;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_NULL_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_ECDSA_WITH_RC4_128_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_NULL_SHA;
    public static final /* enum */ CipherSuite TLS_ECDHE_RSA_WITH_RC4_128_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_NULL_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_ECDSA_WITH_RC4_128_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_NULL_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_RSA_WITH_RC4_128_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_anon_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_anon_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_anon_WITH_NULL_SHA;
    public static final /* enum */ CipherSuite TLS_ECDH_anon_WITH_RC4_128_SHA;
    public static final /* enum */ CipherSuite TLS_EMPTY_RENEGOTIATION_INFO_SCSV;
    public static final /* enum */ CipherSuite TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5;
    public static final /* enum */ CipherSuite TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA;
    public static final /* enum */ CipherSuite TLS_KRB5_EXPORT_WITH_RC4_40_MD5;
    public static final /* enum */ CipherSuite TLS_KRB5_EXPORT_WITH_RC4_40_SHA;
    public static final /* enum */ CipherSuite TLS_KRB5_WITH_3DES_EDE_CBC_MD5;
    public static final /* enum */ CipherSuite TLS_KRB5_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_KRB5_WITH_DES_CBC_MD5;
    public static final /* enum */ CipherSuite TLS_KRB5_WITH_DES_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_KRB5_WITH_RC4_128_MD5;
    public static final /* enum */ CipherSuite TLS_KRB5_WITH_RC4_128_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_EXPORT_WITH_DES40_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_EXPORT_WITH_RC4_40_MD5;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_3DES_EDE_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_AES_128_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_AES_128_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_AES_128_GCM_SHA256;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_AES_256_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_AES_256_CBC_SHA256;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_AES_256_GCM_SHA384;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_DES_CBC_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_NULL_MD5;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_NULL_SHA;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_NULL_SHA256;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_RC4_128_MD5;
    public static final /* enum */ CipherSuite TLS_RSA_WITH_RC4_128_SHA;
    final String javaName;

    static {
        CipherSuite cipherSuite;
        CipherSuite cipherSuite2;
        CipherSuite cipherSuite3;
        CipherSuite cipherSuite4;
        CipherSuite cipherSuite5;
        CipherSuite cipherSuite6;
        CipherSuite cipherSuite7;
        CipherSuite cipherSuite8;
        CipherSuite cipherSuite9;
        CipherSuite cipherSuite10;
        CipherSuite cipherSuite11;
        CipherSuite cipherSuite12;
        CipherSuite cipherSuite13;
        CipherSuite cipherSuite14;
        CipherSuite cipherSuite15;
        CipherSuite cipherSuite16;
        CipherSuite cipherSuite17;
        CipherSuite cipherSuite18;
        CipherSuite cipherSuite19;
        CipherSuite cipherSuite20;
        CipherSuite cipherSuite21;
        CipherSuite cipherSuite22;
        CipherSuite cipherSuite23;
        CipherSuite cipherSuite24;
        CipherSuite cipherSuite25;
        CipherSuite cipherSuite26;
        CipherSuite cipherSuite27;
        CipherSuite cipherSuite28;
        CipherSuite cipherSuite29;
        CipherSuite cipherSuite30;
        CipherSuite cipherSuite31;
        CipherSuite cipherSuite32;
        CipherSuite cipherSuite33;
        CipherSuite cipherSuite34;
        CipherSuite cipherSuite35;
        CipherSuite cipherSuite36;
        CipherSuite cipherSuite37;
        CipherSuite cipherSuite38;
        CipherSuite cipherSuite39;
        CipherSuite cipherSuite40;
        CipherSuite cipherSuite41;
        CipherSuite cipherSuite42;
        CipherSuite cipherSuite43;
        CipherSuite cipherSuite44;
        CipherSuite cipherSuite45;
        CipherSuite cipherSuite46;
        CipherSuite cipherSuite47;
        CipherSuite cipherSuite48;
        CipherSuite cipherSuite49;
        CipherSuite cipherSuite50;
        CipherSuite cipherSuite51;
        CipherSuite cipherSuite52;
        CipherSuite cipherSuite53;
        CipherSuite cipherSuite54;
        CipherSuite cipherSuite55;
        CipherSuite cipherSuite56;
        CipherSuite cipherSuite57;
        CipherSuite cipherSuite58;
        CipherSuite cipherSuite59;
        CipherSuite cipherSuite60;
        CipherSuite cipherSuite61;
        CipherSuite cipherSuite62;
        CipherSuite cipherSuite63;
        CipherSuite cipherSuite64;
        CipherSuite cipherSuite65;
        CipherSuite cipherSuite66;
        CipherSuite cipherSuite67;
        CipherSuite cipherSuite68;
        CipherSuite cipherSuite69;
        CipherSuite cipherSuite70;
        CipherSuite cipherSuite71;
        CipherSuite cipherSuite72;
        CipherSuite cipherSuite73;
        CipherSuite cipherSuite74;
        CipherSuite cipherSuite75;
        CipherSuite cipherSuite76;
        CipherSuite cipherSuite77;
        CipherSuite cipherSuite78;
        CipherSuite cipherSuite79;
        CipherSuite cipherSuite80;
        CipherSuite cipherSuite81;
        CipherSuite cipherSuite82;
        CipherSuite cipherSuite83;
        CipherSuite cipherSuite84;
        CipherSuite cipherSuite85;
        CipherSuite cipherSuite86;
        CipherSuite cipherSuite87;
        CipherSuite cipherSuite88;
        CipherSuite cipherSuite89;
        CipherSuite cipherSuite90;
        CipherSuite cipherSuite91;
        CipherSuite cipherSuite92;
        CipherSuite cipherSuite93;
        CipherSuite cipherSuite94;
        CipherSuite cipherSuite95;
        CipherSuite cipherSuite96;
        TLS_RSA_WITH_NULL_MD5 = cipherSuite96 = new CipherSuite("SSL_RSA_WITH_NULL_MD5", 1, 5246, 6, 10);
        TLS_RSA_WITH_NULL_SHA = cipherSuite95 = new CipherSuite("SSL_RSA_WITH_NULL_SHA", 2, 5246, 6, 10);
        TLS_RSA_EXPORT_WITH_RC4_40_MD5 = cipherSuite94 = new CipherSuite("SSL_RSA_EXPORT_WITH_RC4_40_MD5", 3, 4346, 6, 10);
        TLS_RSA_WITH_RC4_128_MD5 = cipherSuite93 = new CipherSuite("SSL_RSA_WITH_RC4_128_MD5", 4, 5246, 6, 10);
        TLS_RSA_WITH_RC4_128_SHA = cipherSuite92 = new CipherSuite("SSL_RSA_WITH_RC4_128_SHA", 5, 5246, 6, 10);
        TLS_RSA_EXPORT_WITH_DES40_CBC_SHA = cipherSuite91 = new CipherSuite("SSL_RSA_EXPORT_WITH_DES40_CBC_SHA", 8, 4346, 6, 10);
        TLS_RSA_WITH_DES_CBC_SHA = cipherSuite90 = new CipherSuite("SSL_RSA_WITH_DES_CBC_SHA", 9, 5469, 6, 10);
        TLS_RSA_WITH_3DES_EDE_CBC_SHA = cipherSuite89 = new CipherSuite("SSL_RSA_WITH_3DES_EDE_CBC_SHA", 10, 5246, 6, 10);
        TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = cipherSuite88 = new CipherSuite("SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA", 17, 4346, 6, 10);
        TLS_DHE_DSS_WITH_DES_CBC_SHA = cipherSuite87 = new CipherSuite("SSL_DHE_DSS_WITH_DES_CBC_SHA", 18, 5469, 6, 10);
        TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = cipherSuite86 = new CipherSuite("SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA", 19, 5246, 6, 10);
        TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = cipherSuite85 = new CipherSuite("SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA", 20, 4346, 6, 10);
        TLS_DHE_RSA_WITH_DES_CBC_SHA = cipherSuite84 = new CipherSuite("SSL_DHE_RSA_WITH_DES_CBC_SHA", 21, 5469, 6, 10);
        TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = cipherSuite83 = new CipherSuite("SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA", 22, 5246, 6, 10);
        TLS_DH_anon_EXPORT_WITH_RC4_40_MD5 = cipherSuite82 = new CipherSuite("SSL_DH_anon_EXPORT_WITH_RC4_40_MD5", 23, 4346, 6, 10);
        TLS_DH_anon_WITH_RC4_128_MD5 = cipherSuite81 = new CipherSuite("SSL_DH_anon_WITH_RC4_128_MD5", 24, 5246, 6, 10);
        TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA = cipherSuite80 = new CipherSuite("SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA", 25, 4346, 6, 10);
        TLS_DH_anon_WITH_DES_CBC_SHA = cipherSuite79 = new CipherSuite("SSL_DH_anon_WITH_DES_CBC_SHA", 26, 5469, 6, 10);
        TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = cipherSuite78 = new CipherSuite("SSL_DH_anon_WITH_3DES_EDE_CBC_SHA", 27, 5246, 6, 10);
        TLS_KRB5_WITH_DES_CBC_SHA = cipherSuite77 = new CipherSuite("TLS_KRB5_WITH_DES_CBC_SHA", 30, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_WITH_3DES_EDE_CBC_SHA = cipherSuite76 = new CipherSuite("TLS_KRB5_WITH_3DES_EDE_CBC_SHA", 31, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_WITH_RC4_128_SHA = cipherSuite75 = new CipherSuite("TLS_KRB5_WITH_RC4_128_SHA", 32, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_WITH_DES_CBC_MD5 = cipherSuite74 = new CipherSuite("TLS_KRB5_WITH_DES_CBC_MD5", 34, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_WITH_3DES_EDE_CBC_MD5 = cipherSuite73 = new CipherSuite("TLS_KRB5_WITH_3DES_EDE_CBC_MD5", 35, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_WITH_RC4_128_MD5 = cipherSuite72 = new CipherSuite("TLS_KRB5_WITH_RC4_128_MD5", 36, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA = cipherSuite71 = new CipherSuite("TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA", 38, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_EXPORT_WITH_RC4_40_SHA = cipherSuite70 = new CipherSuite("TLS_KRB5_EXPORT_WITH_RC4_40_SHA", 40, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5 = cipherSuite69 = new CipherSuite("TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5", 41, 2712, 6, Integer.MAX_VALUE);
        TLS_KRB5_EXPORT_WITH_RC4_40_MD5 = cipherSuite68 = new CipherSuite("TLS_KRB5_EXPORT_WITH_RC4_40_MD5", 43, 2712, 6, Integer.MAX_VALUE);
        TLS_RSA_WITH_AES_128_CBC_SHA = cipherSuite67 = new CipherSuite("TLS_RSA_WITH_AES_128_CBC_SHA", 47, 5246, 6, 10);
        TLS_DHE_DSS_WITH_AES_128_CBC_SHA = cipherSuite66 = new CipherSuite("TLS_DHE_DSS_WITH_AES_128_CBC_SHA", 50, 5246, 6, 10);
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA = cipherSuite65 = new CipherSuite("TLS_DHE_RSA_WITH_AES_128_CBC_SHA", 51, 5246, 6, 10);
        TLS_DH_anon_WITH_AES_128_CBC_SHA = cipherSuite64 = new CipherSuite("TLS_DH_anon_WITH_AES_128_CBC_SHA", 52, 5246, 6, 10);
        TLS_RSA_WITH_AES_256_CBC_SHA = cipherSuite63 = new CipherSuite("TLS_RSA_WITH_AES_256_CBC_SHA", 53, 5246, 6, 10);
        TLS_DHE_DSS_WITH_AES_256_CBC_SHA = cipherSuite62 = new CipherSuite("TLS_DHE_DSS_WITH_AES_256_CBC_SHA", 56, 5246, 6, 10);
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA = cipherSuite61 = new CipherSuite("TLS_DHE_RSA_WITH_AES_256_CBC_SHA", 57, 5246, 6, 10);
        TLS_DH_anon_WITH_AES_256_CBC_SHA = cipherSuite60 = new CipherSuite("TLS_DH_anon_WITH_AES_256_CBC_SHA", 58, 5246, 6, 10);
        TLS_RSA_WITH_NULL_SHA256 = cipherSuite59 = new CipherSuite("TLS_RSA_WITH_NULL_SHA256", 59, 5246, 7, 21);
        TLS_RSA_WITH_AES_128_CBC_SHA256 = cipherSuite58 = new CipherSuite("TLS_RSA_WITH_AES_128_CBC_SHA256", 60, 5246, 7, 21);
        TLS_RSA_WITH_AES_256_CBC_SHA256 = cipherSuite57 = new CipherSuite("TLS_RSA_WITH_AES_256_CBC_SHA256", 61, 5246, 7, 21);
        TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = cipherSuite56 = new CipherSuite("TLS_DHE_DSS_WITH_AES_128_CBC_SHA256", 64, 5246, 7, 21);
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = cipherSuite55 = new CipherSuite("TLS_DHE_RSA_WITH_AES_128_CBC_SHA256", 103, 5246, 7, 21);
        TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = cipherSuite54 = new CipherSuite("TLS_DHE_DSS_WITH_AES_256_CBC_SHA256", 106, 5246, 7, 21);
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = cipherSuite53 = new CipherSuite("TLS_DHE_RSA_WITH_AES_256_CBC_SHA256", 107, 5246, 7, 21);
        TLS_DH_anon_WITH_AES_128_CBC_SHA256 = cipherSuite52 = new CipherSuite("TLS_DH_anon_WITH_AES_128_CBC_SHA256", 108, 5246, 7, 21);
        TLS_DH_anon_WITH_AES_256_CBC_SHA256 = cipherSuite51 = new CipherSuite("TLS_DH_anon_WITH_AES_256_CBC_SHA256", 109, 5246, 7, 21);
        TLS_RSA_WITH_AES_128_GCM_SHA256 = cipherSuite50 = new CipherSuite("TLS_RSA_WITH_AES_128_GCM_SHA256", 156, 5288, 8, 21);
        TLS_RSA_WITH_AES_256_GCM_SHA384 = cipherSuite49 = new CipherSuite("TLS_RSA_WITH_AES_256_GCM_SHA384", 157, 5288, 8, 21);
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = cipherSuite48 = new CipherSuite("TLS_DHE_RSA_WITH_AES_128_GCM_SHA256", 158, 5288, 8, 21);
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = cipherSuite47 = new CipherSuite("TLS_DHE_RSA_WITH_AES_256_GCM_SHA384", 159, 5288, 8, 21);
        TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = cipherSuite46 = new CipherSuite("TLS_DHE_DSS_WITH_AES_128_GCM_SHA256", 162, 5288, 8, 21);
        TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = cipherSuite45 = new CipherSuite("TLS_DHE_DSS_WITH_AES_256_GCM_SHA384", 163, 5288, 8, 21);
        TLS_DH_anon_WITH_AES_128_GCM_SHA256 = cipherSuite44 = new CipherSuite("TLS_DH_anon_WITH_AES_128_GCM_SHA256", 166, 5288, 8, 21);
        TLS_DH_anon_WITH_AES_256_GCM_SHA384 = cipherSuite43 = new CipherSuite("TLS_DH_anon_WITH_AES_256_GCM_SHA384", 167, 5288, 8, 21);
        TLS_EMPTY_RENEGOTIATION_INFO_SCSV = cipherSuite42 = new CipherSuite("TLS_EMPTY_RENEGOTIATION_INFO_SCSV", 255, 5746, 6, 14);
        TLS_ECDH_ECDSA_WITH_NULL_SHA = cipherSuite41 = new CipherSuite("TLS_ECDH_ECDSA_WITH_NULL_SHA", 49153, 4492, 7, 14);
        TLS_ECDH_ECDSA_WITH_RC4_128_SHA = cipherSuite40 = new CipherSuite("TLS_ECDH_ECDSA_WITH_RC4_128_SHA", 49154, 4492, 7, 14);
        TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = cipherSuite39 = new CipherSuite("TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA", 49155, 4492, 7, 14);
        TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = cipherSuite38 = new CipherSuite("TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA", 49156, 4492, 7, 14);
        TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = cipherSuite37 = new CipherSuite("TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA", 49157, 4492, 7, 14);
        TLS_ECDHE_ECDSA_WITH_NULL_SHA = cipherSuite36 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_NULL_SHA", 49158, 4492, 7, 14);
        TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = cipherSuite35 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_RC4_128_SHA", 49159, 4492, 7, 14);
        TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = cipherSuite34 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA", 49160, 4492, 7, 14);
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = cipherSuite33 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", 49161, 4492, 7, 14);
        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = cipherSuite32 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", 49162, 4492, 7, 14);
        TLS_ECDH_RSA_WITH_NULL_SHA = cipherSuite31 = new CipherSuite("TLS_ECDH_RSA_WITH_NULL_SHA", 49163, 4492, 7, 14);
        TLS_ECDH_RSA_WITH_RC4_128_SHA = cipherSuite30 = new CipherSuite("TLS_ECDH_RSA_WITH_RC4_128_SHA", 49164, 4492, 7, 14);
        TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = cipherSuite29 = new CipherSuite("TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA", 49165, 4492, 7, 14);
        TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = cipherSuite28 = new CipherSuite("TLS_ECDH_RSA_WITH_AES_128_CBC_SHA", 49166, 4492, 7, 14);
        TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = cipherSuite27 = new CipherSuite("TLS_ECDH_RSA_WITH_AES_256_CBC_SHA", 49167, 4492, 7, 14);
        TLS_ECDHE_RSA_WITH_NULL_SHA = cipherSuite26 = new CipherSuite("TLS_ECDHE_RSA_WITH_NULL_SHA", 49168, 4492, 7, 14);
        TLS_ECDHE_RSA_WITH_RC4_128_SHA = cipherSuite25 = new CipherSuite("TLS_ECDHE_RSA_WITH_RC4_128_SHA", 49169, 4492, 7, 14);
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = cipherSuite24 = new CipherSuite("TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA", 49170, 4492, 7, 14);
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = cipherSuite23 = new CipherSuite("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", 49171, 4492, 7, 14);
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = cipherSuite22 = new CipherSuite("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", 49172, 4492, 7, 14);
        TLS_ECDH_anon_WITH_NULL_SHA = cipherSuite21 = new CipherSuite("TLS_ECDH_anon_WITH_NULL_SHA", 49173, 4492, 7, 14);
        TLS_ECDH_anon_WITH_RC4_128_SHA = cipherSuite20 = new CipherSuite("TLS_ECDH_anon_WITH_RC4_128_SHA", 49174, 4492, 7, 14);
        TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = cipherSuite19 = new CipherSuite("TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA", 49175, 4492, 7, 14);
        TLS_ECDH_anon_WITH_AES_128_CBC_SHA = cipherSuite18 = new CipherSuite("TLS_ECDH_anon_WITH_AES_128_CBC_SHA", 49176, 4492, 7, 14);
        TLS_ECDH_anon_WITH_AES_256_CBC_SHA = cipherSuite17 = new CipherSuite("TLS_ECDH_anon_WITH_AES_256_CBC_SHA", 49177, 4492, 7, 14);
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = cipherSuite16 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256", 49187, 5289, 7, 21);
        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = cipherSuite15 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", 49188, 5289, 7, 21);
        TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = cipherSuite14 = new CipherSuite("TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256", 49189, 5289, 7, 21);
        TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = cipherSuite13 = new CipherSuite("TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384", 49190, 5289, 7, 21);
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = cipherSuite12 = new CipherSuite("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", 49191, 5289, 7, 21);
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = cipherSuite11 = new CipherSuite("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", 49192, 5289, 7, 21);
        TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = cipherSuite10 = new CipherSuite("TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256", 49193, 5289, 7, 21);
        TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = cipherSuite9 = new CipherSuite("TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384", 49194, 5289, 7, 21);
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = cipherSuite8 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", 49195, 5289, 8, 21);
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = cipherSuite7 = new CipherSuite("TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", 49196, 5289, 8, 21);
        TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = cipherSuite6 = new CipherSuite("TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256", 49197, 5289, 8, 21);
        TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = cipherSuite5 = new CipherSuite("TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384", 49198, 5289, 8, 21);
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = cipherSuite4 = new CipherSuite("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", 49199, 5289, 8, 21);
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = cipherSuite3 = new CipherSuite("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", 49200, 5289, 8, 21);
        TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = cipherSuite2 = new CipherSuite("TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256", 49201, 5289, 8, 21);
        TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = cipherSuite = new CipherSuite("TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384", 49202, 5289, 8, 21);
        $VALUES = new CipherSuite[]{cipherSuite96, cipherSuite95, cipherSuite94, cipherSuite93, cipherSuite92, cipherSuite91, cipherSuite90, cipherSuite89, cipherSuite88, cipherSuite87, cipherSuite86, cipherSuite85, cipherSuite84, cipherSuite83, cipherSuite82, cipherSuite81, cipherSuite80, cipherSuite79, cipherSuite78, cipherSuite77, cipherSuite76, cipherSuite75, cipherSuite74, cipherSuite73, cipherSuite72, cipherSuite71, cipherSuite70, cipherSuite69, cipherSuite68, cipherSuite67, cipherSuite66, cipherSuite65, cipherSuite64, cipherSuite63, cipherSuite62, cipherSuite61, cipherSuite60, cipherSuite59, cipherSuite58, cipherSuite57, cipherSuite56, cipherSuite55, cipherSuite54, cipherSuite53, cipherSuite52, cipherSuite51, cipherSuite50, cipherSuite49, cipherSuite48, cipherSuite47, cipherSuite46, cipherSuite45, cipherSuite44, cipherSuite43, cipherSuite42, cipherSuite41, cipherSuite40, cipherSuite39, cipherSuite38, cipherSuite37, cipherSuite36, cipherSuite35, cipherSuite34, cipherSuite33, cipherSuite32, cipherSuite31, cipherSuite30, cipherSuite29, cipherSuite28, cipherSuite27, cipherSuite26, cipherSuite25, cipherSuite24, cipherSuite23, cipherSuite22, cipherSuite21, cipherSuite20, cipherSuite19, cipherSuite18, cipherSuite17, cipherSuite16, cipherSuite15, cipherSuite14, cipherSuite13, cipherSuite12, cipherSuite11, cipherSuite10, cipherSuite9, cipherSuite8, cipherSuite7, cipherSuite6, cipherSuite5, cipherSuite4, cipherSuite3, cipherSuite2, cipherSuite};
    }

    private CipherSuite(String string3, int n2, int n3, int n4, int n5) {
        this.javaName = string3;
    }

    public static CipherSuite forJavaName(String object) {
        if (object.startsWith("SSL_")) {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.append("TLS_");
            stringBuilder.append(object.substring(4));
            object = CipherSuite.valueOf(stringBuilder.toString());
        } else {
            object = CipherSuite.valueOf(object);
        }
        return object;
    }

    public static CipherSuite valueOf(String string2) {
        return Enum.valueOf(CipherSuite.class, string2);
    }

    public static CipherSuite[] values() {
        return (CipherSuite[])$VALUES.clone();
    }

    public String javaName() {
        return this.javaName;
    }
}

